live_config_reload: true

font:
  normal:
    family: JetBrainsMonoNL Nerd Font Mono
    style: Regular
  size: 10.0

window:
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  decoration: none

selection:
  save_to_clipboard: true
env:
  TERM: xterm-256color

colors:
  name: TokyoNight Day
  author: Folke
  # Default colors
  primary:
    background: "0xe1e2e7"
    foreground: "0x3760bf"

  # Normal colors
  normal:
    black: "0xe9e9ed"
    red: "0xf52a65"
    green: "0x587539"
    yellow: "0x8c6c3e"
    blue: "0x2e7de9"
    magenta: "0x9854f1"
    cyan: "0x007197"
    white: "0x6172b0"

  # Bright colors
  bright:
    black: "0xa1a6c5"
    red: "0xf52a65"
    green: "0x587539"
    yellow: "0x8c6c3e"
    blue: "0x2e7de9"
    magenta: "0x9854f1"
    cyan: "0x007197"
    white: "0x3760bf"

  indexed_colors:
    - { index: 16, color: "0xb15c00" }
    - { index: 17, color: "0xc64343" }
window:
  opacity: 0.9
